language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
